"""initial schema: users households pantry_items

Revision ID: 4f8416b1f344
Revises: c8d4f48fdf72
Create Date: 2026-06-05 11:43:48.192593
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4f8416b1f344'
down_revision: Union[str, None] = 'c8d4f48fdf72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pantry_items', sa.Column('added_by_user_id', sa.UUID(), nullable=True))
    op.add_column('pantry_items', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('pantry_items', sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pantry_items', sa.Column('purchase_date', sa.Date(), nullable=True))
    op.add_column('pantry_items', sa.Column('quantity_purchased', sa.Numeric(precision=10, scale=3), nullable=True))
    op.create_index(op.f('ix_pantry_items_added_by_user_id'), 'pantry_items', ['added_by_user_id'], unique=False)
    op.create_index(op.f('ix_pantry_items_status'), 'pantry_items', ['status'], unique=False)
    op.create_foreign_key(None, 'pantry_items', 'users', ['added_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pantry_items', type_='foreignkey')
    op.drop_index(op.f('ix_pantry_items_status'), table_name='pantry_items')
    op.drop_index(op.f('ix_pantry_items_added_by_user_id'), table_name='pantry_items')
    op.drop_column('pantry_items', 'quantity_purchased')
    op.drop_column('pantry_items', 'purchase_date')
    op.drop_column('pantry_items', 'purchase_price')
    op.drop_column('pantry_items', 'status')
    op.drop_column('pantry_items', 'added_by_user_id')
    # ### end Alembic commands ###
